name: NPM react-use-modal release
on:
  push:
    tags:
      - 'use-modal/v*'

env:
  cache-version: v1

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
          scope       : '@styless-ui'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ env.cache-version }}-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ env.cache-version }}-${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ env.cache-version }}-${{ runner.os }}-build-
            ${{ env.cache-version }}-${{ runner.os }}-

      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Run Build
        run: npm run build
        env:
          CI: false

      - name: Publish
        run : npm publish --access=public --workspace packages/use-modal
        env :
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
